version: '3.9'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7.35
    environment:
      MYSQL_DATABASE: php_project
      MYSQL_USER: admin
      MYSQL_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "33061:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
